// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvhcxmgcsemnbzjcscjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52aGN4bWdjc2VtbmJ6amNzY2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDIxNjksImV4cCI6MjA3NDM3ODE2OX0.ENWrciVc2w8Wxc4n7tSM6aPakjHve7ewWyW7znPMzoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});